title: Jillian Andrea Juat Portfolio # your name (or website title) here
logo: ![Jillian Andrea Juat](jjuat-profile.webp)
description: > # your text below (remove <br> elements if you don't need line breaks)
Portfolio Website of Jillian Andrea Juat

  <br><br>
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/about">About</a>
  <br><br> 
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/portfolio">Portfolio</a>
  <br><br>
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/subscribe">Subscribe</a>
  <a href="https://www.linkedin.com/in/jillian-andrea-juat-376137253/">LinkedIn</a>
  <a href="https://github.com/jdj25">GitHub</a>
  <br><br>
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/privacy_policy">Privacy Policy</a>
  
theme: jekyll-theme-minimal
google_analytics: G-W20C1L4HEH # your Google Analytics tracking ID here
