title: Jill Juat # your name (or website title) here
logo: # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 This is my portfolio website

  <br><br>
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/about">About</a>
  <br><br> 
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/portfolio">Portfolio</a>
  <br><br>
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/subscribe">Subscribe</a>
  <br><br>
  <a href="https://jdj25.github.io/jdj25-is218-final-portfolio/privacy_policy">Privacy Policy</a>
  
theme: jekyll-theme-minimal
google_analytics: G-W20C1L4HEH # your Google Analytics tracking ID here
